name: CI

on: pull_request

jobs:

  lint:
    name: Lint check
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Lint check
      run: npm run lint

  build:
    name: Build check
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Build check
      run: npm run compile

  size:
    name: Size check
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Size check
      run: npm run vscode:prepublish

  test-stable:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: Test with VS Code stable on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci && cd test-workspaces && npm ci && cd customized && npm ci
    - name: Test check
      run: npm run ci:stable
      if: matrix.os != 'ubuntu-latest'
    - name: Required for Code display on Linux
      run: sudo apt-get install xvfb
      if: matrix.os == 'ubuntu-latest'
    - name: Test check
      run: xvfb-run --auto-servernum npm run ci:stable
      if: matrix.os == 'ubuntu-latest'

  test-minimal:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: Test with VS Code 1.56 on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci && cd test-workspaces && npm ci && cd customized && npm ci
    - name: Test check
      run: npm run ci:minimal
      if: matrix.os != 'ubuntu-latest'
    - name: Required for Code display on Linux
      run: sudo apt-get install xvfb
      if: matrix.os == 'ubuntu-latest'
    - name: Test check
      run: xvfb-run --auto-servernum npm run ci:minimal
      if: matrix.os == 'ubuntu-latest'

  test-insiders:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: Test with VS Code insiders on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci && cd test-workspaces && npm ci && cd customized && npm ci
    - name: Test check
      run: npm run ci:insiders
      if: matrix.os != 'ubuntu-latest'
    - name: Required for Code display on Linux
      run: sudo apt-get install xvfb
      if: matrix.os == 'ubuntu-latest'
    - name: Test check
      run: xvfb-run --auto-servernum npm run ci:insiders
      if: matrix.os == 'ubuntu-latest'
